export const categories = [
  {
    id: "1",
    name: "উপন্যাস",
    description: "উপন্যাস বা গল্প বই সমূহ",
    banglish_name: "uponnyash",
    slug: "uponnyash",
    hidden: false,
    image: '/books/b (1).jpg',
    banner: "/books/b (1).jpg",
  },
  {
    id: "2",
    name: "কবিতা",
    description: "কবিতা বই সমূহ",
    banglish_name: "kobita",
    slug: "kobita",
    hidden: false,
    image: "/books/b (2).jpg",
    banner: "/books/b (2).jpg",
  },
  {
    id: "3",
    name: "গবেষণা",
    description: "গবেষণা ও বিজ্ঞান বই সমূহ",
    banglish_name: "gobeshona",
    slug: "gobeshona",
    hidden: false,
    image: "/books/b (3).jpg",
    banner: "/books/b (3).jpg",
  },
  {
    id: "4",
    name: "ইতিহাস",
    description: "ইতিহাস বই সমূহ",
    banglish_name: "itihas",
    slug: "itihas",
    hidden: false,
    image: "/books/b (4).jpg",
    banner: "/books/b (4).jpg",
  },
  {
    id: "5",
    name: "বাংলা সাহিত্য",
    description: "বাংলা সাহিত্য বই সমূহ",
    banglish_name: "bangla_sahitya",
    slug: "bangla-sahitya",
    hidden: false,
    image: "/books/b (5).jpg",
    banner: "/books/b (5).jpg",
  },
  {
    id: "6",
    name: "উপন্যাস (ইংরেজি)",
    description: "ইংরেজি ভাষার উপন্যাস বই সমূহ",
    banglish_name: "english_novels",
    slug: "english-novels",
    hidden: false,
    image: "/books/b (6).jpg",
    banner: "/books/b (6).jpg",
  },
  {
    id: "7",
    name: "কমিক্স",
    description: "কমিক্স ও গ্রাফিক নভেল সমূহ",
    banglish_name: "comics",
    slug: "comics",
    hidden: false,
    image: "/books/b (7).jpg",
    banner: "/books/b (7).jpg",
  },
  {
    id: "8",
    name: "প্রযুক্তি",
    description: "প্রযুক্তি ও কম্পিউটার বই সমূহ",
    banglish_name: "technology",
    slug: "technology",
    hidden: false,
    image: "/books/b (8).jpg",
    banner: "/books/b (8).jpg",
  },
  {
    id: "9",
    name: "স্বাস্থ্য ও সেবা",
    description: "স্বাস্থ্য ও সেবা সম্বন্ধীয় বই সমূহ",
    banglish_name: "health_care",
    slug: "health-care",
    hidden: false,
    image: "/books/b (9).jpg",
    banner: "/books/b (9).jpg",
  },
  {
    id: "10",
    name: "বিজ্ঞান কথা",
    description: "বিজ্ঞান ও প্রযুক্তি সম্বন্ধীয় বই সমূহ",
    banglish_name: "science_talks",
    slug: "science-talks",
    hidden: false,
    image: "/books/b (10).jpg",
    banner: "/books/b (10).jpg",
  },
  {
    id: "11",
    name: "রহস্যময় উপন্যাস",
    description: "রহস্যময় উপন্যাস বই সমূহ",
    banglish_name: "mystery_novels",
    slug: "mystery-novels",
    hidden: false,
    image: "/books/b (11).jpg",
    banner: "/books/b (11).jpg",
  },
  {
    id: "12",
    name: "ধর্মীয় গ্রন্থ",
    description: "বিভিন্ন ধর্মের গ্রন্থ সমূহ",
    banglish_name: "religious_books",
    slug: "religious-books",
    hidden: false,
    image: "/books/b (12).jpg",
    banner: "/books/b (12).jpg",
  },
  {
    id: "13",
    name: "শিক্ষা",
    description: "শিক্ষা ও পড়াশোনা সম্বন্ধীয় বই সমূহ",
    banglish_name: "education",
    slug: "education",
    hidden: false,
    image: "/books/b (13).jpg",
    banner: "/books/b (13).jpg",
  },
  {
    id: "14",
    name: "কৃষি ও প্রকৃতি",
    description: "কৃষি ও প্রকৃতি সম্বন্ধীয় বই সমূহ",
    banglish_name: "agriculture_nature",
    slug: "agriculture-nature",
    hidden: false,
    image: "/books/b (14).jpg",
    banner: "/books/b (14).jpg",
  },
  {
    id: "15",
    name: "ক্রীড়া ও খেলাধুলা",
    description: "ক্রীড়া ও খেলাধুলা সম্বন্ধীয় বই সমূহ",
    banglish_name: "sports_recreation",
    slug: "sports-recreation",
    hidden: false,
    image: "/books/b (15).jpg",
    banner: "/books/b (15).jpg",
  },
];
