export const users = [
  {
    id: 1,
    name: "Fahad Ahmed",
    role: "Customer",
    email: "xyz03@gmail.com",
    phoneNumber: "01716817890",
    gender: "Male",
  },
  {
    id: 2,
    name: "Fahad Ahmed",
    role: "Customer",
    email: "xyz03@gmail.com",
    phoneNumber: "01716817890",
    gender: "Male",
  },
  {
    id: 3,
    name: "Fahad Ahmed",
    role: "Customer",
    email: "xyz03@gmail.com",
    phoneNumber: "01716817890",
    gender: "Male",
  },
  {
    id: 4,
    name: "Fahad Ahmed",
    role: "Customer",
    email: "xyz03@gmail.com",
    phoneNumber: "01716817890",
    gender: "Male",
  },
  {
    id: 5,
    name: "Fahad Ahmed",
    role: "Customer",
    email: "xyz03@gmail.com",
    phoneNumber: "01716817890",
    gender: "Male",
  },
  {
    id: 6,
    name: "Fahad Ahmed",
    role: "Customer",
    email: "xyz03@gmail.com",
    phoneNumber: "01716817890",
    gender: "Male",
  },
];
