import { BookAdmin } from '@/interface';

export const initialBook: BookAdmin = {
  name: "",
  slug: "",
  authors: [],
  categories: [],
  publisher: null,
  regular_price: 0,
  sale_price: 0,
  manage_stock: true,
  quantity: 1,
  in_stock: true,
  pre_order: false,
  shipping_required: true,
  description: null,
  short_description: null,
  images: [],
  is_used: false,
  condition: "new",
  edition: null,
  notes: null,
  cover: null,
  translators: [],
  language: null,
  isbn: null,
  no_of_pages: null,
  country: null,
  tags: [],
  bar_code: null,
  weight_in_gm: 0,

  is_draft: false,
  is_featured: false,
  is_must_read: false,
  is_vintage: false,
  is_islamic: false,
  is_translated: false,
  is_recommended: false,
  is_big_sale: false,
  is_popular: false,

  sku: "",
  cost: 0,
  stock_location: "mirpur-11",
  shelf: null,
  row_col: null,
};
