export const items = [
    {
      name: "অপুর সংকেত",
      author: "Bibhutibhushan Bandopadhyay",
      regular_price: 1000,
      sell_price: 250,
      src: "/books/b (1).jpg",
      stock: 8,
      condition: "New",
      slug: "apura-sanket",
    },
    {
      name: "ফেলুদা সমগ্র",
      author: "Satyajit Ray",
      regular_price: 1500,
      sell_price: 400,
      src: "/books/b (2).jpg",
      stock: 10,
      condition: "OLD-Like New",
      slug: "feluda-samagra",
    },
    {
      name: "পথের পাঁচালী",
      author: "Bibhutibhushan Bandopadhyay",
      regular_price: 1200,
      sell_price: 300,
      src: "/books/b (3).jpg",
      stock: 6,
      condition: "OLD-Good Enough",
      slug: "pather-panchali",
    },
    {
      name: "শঙ্কু সমগ্র",
      author: "Samaresh Majumdar",
      regular_price: 1100,
      sell_price: 280,
      src: "/books/b (4).jpg",
      stock: 7,
      condition: "New",
      slug: "shonku-samagra",
    },
    {
      name: "গোপাল ভার",
      author: "Sarat Chandra Chattopadhyay",
      regular_price: 1300,
      sell_price: 350,
      src: "/books/b (5).jpg",
      stock: 9,
      condition: "OLD-Readeble",
      slug: "gopal-bhar",
    },
    {
      name: "দীপুর জল",
      author: "Tarashankar Bandopadhyay",
      regular_price: 1400,
      sell_price: 380,
      src: "/books/b (6).jpg",
      stock: 5,
      condition: "New",
      slug: "deepur-jol",
    },
  ];
  

export const reviews = [
  {
    dp: "/reviews/1.png",
    author: "John Doe",
    date: "2023-01-15",
    src: "/reviews/1.png",
    description: "Amazing book! I couldn't put it down. Highly recommended!",
  },
  {
    dp: "/reviews/2.png",
    author: "Jane Smith",
    date: "2023-02-05",
    src: "/reviews/2.png",
    description: "A captivating read. The characters are well-developed, and the plot keeps you hooked from start to finish.",
  },
  {
    dp: "/reviews/3.png",
    author: "Alex Johnson",
    date: "2023-03-20",
    src: "/reviews/3.png",
    description: "This book exceeded my expectations. The storytelling is excellent, and it left a lasting impression on me.",
  },
  {
    dp: "/reviews/4.png",
    author: "Emily White",
    date: "2023-04-10",
    src: "/reviews/4.png",
    description: "An emotional journey. The author beautifully explores complex themes. I felt deeply connected to the characters.",
  },
  {
    dp: "/reviews/5.png",
    author: "Michael Brown",
    date: "2023-05-25",
    src: "/reviews/5.png",
    description: "Well-written and thought-provoking. It's a book that stays with you, making you reflect on life and relationships.",
  },
  {
    dp: "/reviews/6.png",
    author: "Michael Brown",
    date: "2023-05-25",
    src: "/reviews/6.png",
    description: "Well-written and thought-provoking. It's a book that stays with you, making you reflect on life and relationships.",
  },
]